### PR TITLE
Add the share your ideas page

### PR DESCRIPTION
**Pull request by mark-pkgflow**
Card: [Build the 'share your ideas' page](https://trello.com/c/beGBhI6a)

This PR implements the 'Share Your Ideas' page. A new button has been added, consistent with the 'Explore all resources' style, linking directly to the feedback form. The form opens in the same window.

image

### CODE REVIEW

**Comment by mark-pkgflow** [comment]
[Build the 'share your ideas' page](https://trello.com/c/beGBhI6a/293-build-the-share-your-ideas-page)

**Review by AbigailMcP — COMMENTED** [review]
This bit looks like it needs tweaking a bit (the icon needs to be bigger and aligned with the title):

Screenshot 2024-02-06 at 09 20 28

It looks like it's the same styling as the feedback section we've already built, so you should be able to reuse the classes from here:

Screenshot 2024-02-06 at 09 27 01

Also, the 'Share your ideas' button font needs to be bold, similar to the homepage 'Explore all resources' button.

**Comment by claire-hughez** [comment]
Looks good, few points other than Abi's here:
1) When the button is clicked, it turns green. Is this intended? Might be with checking with Lauren. I don't think we should spend loads of time trying to 'break' existing GDS components, so potentially we consider moving to green if this isn't easily fixable or intended.
2) Please can we expand the text under the H1 to share your ideas to match the 'Explore all resources page'? This is what we're doing when there's not an image.

**Comment by AbigailMcP** [comment]
> > This bit looks like it needs tweaking a bit (the icon needs to be bigger and aligned with the title):
> > It looks like it's the same styling as the feedback section we've already built, so you should be able to reuse the classes from here:
> 
> I actually had this perfect locally, but just discovered that it wasn't pushed 🤦 It is now.

I think the icon is still too small - needs to be the same size as the feedback icons which are 67px.

**Comment by claire-hughez** [comment]
@mark-pkgflow 
On the text width, for the second question, I'm basically suggesting to copy whatever text width is used on this page:

https://improve-workload-and-wellbeing-for-school-staff.education.gov.uk/explore-all-resources/identify-workload-issues/

But we are talking about the same chunk of text. Happy to jump on a call if needed!

**Review by AbigailMcP — APPROVED** [review]

**Pull request merged**
