### PR TITLE
Add communications page and styles

### PR DESCRIPTION
**Pull request by AbigailMcP**
# Changes made in this PR

Adds the communication workload reduction topic page linked to from the Address workload issues page.

Creates a resource-card partial.

Adds info-box and styling.

# Guidance to review

Head to 'Workload reduction toolkit' -> 'Address workload issues' -> 'Communications'.
Check the page looks like the prototype.

Screenshot 2024-01-18 at 16 10 34

Screenshot 2024-01-18 at 16 10 37

Screenshot 2024-01-18 at 16 10 41

### CODE REVIEW

**Review by mark-pkgflow — APPROVED** [review]
Nice

**Comment by AbigailMcP** [comment]
[Create workload topic page for 'Communications'](https://trello.com/c/LOMKkIbH/250-create-workload-topic-page-for-communications)

**Comment by claire-hughez** [comment]
This looks good to me!

There's still some of the spacing stuff you talked about Abi that I think Lauren is getting back to you on. I'll leave that for Lauren to comment on more fully, just from observing it seems breaks/spacing might be a bit too tall/large between stuff?

**Comment by lauren-oseni-2** [comment]
Looks great! Just need to remove 'activity time' on the communications presentation tile and minimise the spacing a tad. Please see my style guide to help :)

**Comment by AbigailMcP** [comment]
Removed 'activity time', updated spacing between elements, removed font size overrides across site to use govuk default (19px on wide screens, 16px on small screens)

**Comment by AbigailMcP** [comment]
[Create workload topic page for 'Communications'](https://trello.com/c/LOMKkIbH/250-create-workload-topic-page-for-communications)

**Comment by claire-hughez** [comment]
Just checked font. We're good to go. It's made the share your ideas box slightly spaced weirdly but that area is changing a bit in another ticket, so fine to merge.

I notice the images aren't working again - is that just because its a preview environment?

**Pull request merged**
