### PR TITLE
[267] Explore resources page(/s)

### PR DESCRIPTION
**Pull request by AbigailMcP**
## Changes in this PR

- Creates a common layout for all explore resources pages
- Adds each explore page,  linked from the Topic list down the left hand side
- Re-jigs base/ default layouts so the base can be reused in the new explore resources one
- Remove `resource-tag` css and use altered `govuk-tag` html and css instead

## Trello card

https://trello.com/c/JbF1vZRA/267-create-explore-all-resources-page

## Guidance to review

- Head to 'Explore resources' in the nav
- Check each of the links down the LHS
- **The links to the individual resourcs just link to the homepage since they're not built yet. This means they might show in purple because you've already visited that page. When we add the resources, the links will be blue if unvisited. This is the standard for govuk links.**
- **I haven't added the count of resources yet - do we need this if everything is static? Will the resource count ever change? If people add/remove a resource and this is static, they'll need to remember to update the count.**

Screenshot 2024-01-29 at 10 39 54

### CODE REVIEW

**Comment by AbigailMcP** [comment]
[Create 'Explore all resources' page](https://trello.com/c/JbF1vZRA/267-create-explore-all-resources-page)

**Review by mark-pkgflow — APPROVED** [review]
LGTM

**Comment by claire-hughez** [comment]
Hello! Looks fab. Just a couple bits:
- The 'explore all resources' button on the homepage should link to this new 'Explore all resources' page.
Screenshot 2024-01-29 at 14 42 54
- The positioning of the text that starts 'This is a set of free workload reduction and wellbeing resources...' looks odd to me so worth querying with design. I think because there's no image. A question for design - do we want an image? Is it fine like this?
- 'Evaluate workload impact' should read 'Evaluate workload measures'. Sorry, this must have got missed in the Figma prototype when the wording was changed.
- '[Switching to online parents' evenings]' should link to the existing page you've done for this Abi. Is this because the other ticket isn't merged yet?

Not really a 'review', but a point worth making: This page will change a lot as we add each individual resource to the service. Some of the content will be tweaked for resource names and reading times will be added. Just flagging in case it impacts anything else.

**Comment by lauren-oseni-2** [comment]
We may struggle to find another image to include to this page, so I'd say just leave it how it is. The width of the paragraph however could be adjusted to look better. Could the width of that text box be: 649 px? I believe it's currently at: 496 px

**Comment by AbigailMcP** [comment]
@lauren-oseni-2 @claire-hughez - updated as per your review points, including linking to now merged case study page (parents evenings)

**Comment by claire-hughez** [comment]
This looks great to me Abi and links simply to the individual resource. :)

**Pull request merged**
